version: '3.8'

services:
  environment:
    # 컨테이너 이름 (docker ps 에서 확인할 때 보기 쉬움)
    container_name: javame-environment-local

    # 현재 디렉토리를 빌드 컨텍스트로 사용하고, Dockerfile 을 기준으로 이미지 빌드
    build:
      context: .  # 해당 서비스의 프로젝트 루트 디렉토리
      dockerfile: Dockerfile

    # 호스트 → 컨테이너 포트 매핑 (host:container)
    ports:
      - "10273:10273"

    # Spring Boot 실행 시 사용할 프로파일 지정
    environment:
      - SPRING_PROFILES_ACTIVE=dev

    # 사용할 Docker 네트워크 지정 (공유 네트워크로 설정되어 있어야 다른 컨테이너들과 통신 가능)
    networks:
      - local-net

# 외부에서 미리 생성해 둔 local-net 네트워크를 참조합니다.
# 모든 서비스가 동일한 local-net 을 사용하면 서로 컨테이너 이름으로 통신 가능 (예: http://eureka:10280 에 서비스 등록 가능)
networks:
  local-net:
    external: true
